from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

app = Flask(__name__, template_folder="./templates")
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = "users.login"

# Generated by secrets.token_hex() function with the size of 16 bytes
app.config["SECRET_KEY"] = "e10e19b72b6198986281a90d5b346e68"

from web_app.main.routes import main
from web_app.users.routes import users
from web_app.books.routes import books

app.register_blueprint(main)
app.register_blueprint(users)
app.register_blueprint(books)
