from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

app = Flask(__name__, template_folder="./templates")
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = "login"
# login_manager.login_message_category = ""

#Generated by secrets.token_hex() function with the size of 16 bytes
app.config["SECRET_KEY"] = "e10e19b72b6198986281a90d5b346e68"

from WebApp import routes
