from flask import Flask
from flask_bcrypt import Bcrypt

app = Flask(__name__, template_folder="./templates")
bcrypt = Bcrypt(app)

#Generated by secrets.token_hex() function with the size of 16 bytes
app.config["SECRET_KEY"] = "e10e19b72b6198986281a90d5b346e68"

from WebApp import routes
